### ISSUE TITLE
use '

### ISSUE THREAD

**Issue by timelyportfolio** [osazuwa223/igraphr#3]
Just found this through Twitter and can't wait to spend a couple days with it.  If you're not aware, @rich-iannone has made [`DiagrammeR`](https://github.com/rich-iannone/DiagrammeR), a [`htmlwidget`](http://htmlwidgets.org) that uses `viz.js` to produce graphviz plots that can be used in traditional R contexts and also easily added to web content.   Would you be interested in this?  Happy to help/submit pull if yes.

**Comment by robertness** [comment]
How can I support [@rich-iannone](https://github.com/rich-iannone)'s project?  Supposing I made a vignette that work with DiagrammeR?

**Comment by timelyportfolio** [comment]
I will be happy to do it.  I just wanted to make sure you would be amenable to it.
